/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practica3;

import java.io.IOException;
import java.util.List;

import net.sourceforge.tess4j.TesseractException;

import java.awt.AWTException;

import practica3.service.Program;
import practica3.domain.Game;

public class App {
    public static void main(String[] args) throws AWTException, InterruptedException, TesseractException {
        try {
            Program program = new Program();
            program.viewInfo();
            Game g = program.listData("Reversi");
            List<Game> games = program.listGamesInLocation("B");
        } catch (IOException e) {
            e.printStackTrace();
        }    
    }
}
